# Generated by Django 5.0.2 on 2024-02-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtraroms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='custommod',
            table='xtraroms_api_mods',
        ),
        migrations.AlterModelTable(
            name='customrom',
            table='xtraroms_api_roms',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='xtraroms_api_userprofile',
        ),
    ]
