# Generated by Django 5.0 on 2024-02-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtraroms', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
